version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: livraria-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: livraria
    ports:
      - "5432:5432"
    volumes:
      # Volume persistente para armazenar dados do banco
      - postgres_data:/var/lib/postgresql/data
      # Script SQL para inicialização automática
      - ./scripts/livraria.sql:/docker-entrypoint-initdb.d/livraria.sql:ro

volumes:
  postgres_data:
